version: '3'

services:
  alice:
    image: thierrysans/alice:malicious-gateway
    container_name: alice
    networks:
      internal:
        ipv4_address: 10.0.0.2
    cap_add:
      - NET_ADMIN

  mallory:
      image: thierrysans/mallory:malicious-gateway
      container_name: mallory
      tty: true
      restart: always
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN
      volumes:
          - .:/shared
      networks:
        internal:
          ipv4_address: 10.0.0.3
        external:
          ipv4_address: 10.0.1.3
          
  wireshark:
    image: thierrysans/wireshark:malicious-gateway
    container_name: wireshark
    tty: true
    network_mode: service:mallory

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
  external:
    driver: bridge
    ipam:
       config:
        - subnet: 10.0.1.0/24
