version: '3'

services:
  alice:
    image: thierrysans/alice:arp-spoofing
    container_name: alice
    networks:
      legitimate:
        ipv4_address: 10.0.0.2
    cap_add:
      - NET_ADMIN

  mallory:
      image: thierrysans/mallory:arp-spoofing
      container_name: mallory
      tty: true
      restart: always
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN
      volumes:
          - .:/shared
      networks:
        legitimate:
          ipv4_address: 10.0.0.3
        malicious:
          ipv4_address: 10.0.1.3

networks:
  legitimate:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
  malicious:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
