version: '3'

services:
  alice:
    image: thierrysans/alice:packet-sniffing
    container_name: alice
    networks:
      channel:
        ipv4_address: 10.0.0.2

  mallory:
      image: thierrysans/mallory:packet-sniffing
      container_name: mallory
      tty: true
      restart: always
      network_mode: service:alice

networks:
  channel:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/28
