version: '3'

services:
  microblog:
    image: thierrysans/microblog:latest
    container_name: microblog
    ports:
      - "8080:80"
    networks:
      channel:
        ipv4_address: 10.0.0.2
        
  alice:
    image: thierrysans/alice:csrf
    container_name: alice
    tty: true
    shm_size: '1gb'
    sysctls:
        - net.ipv6.conf.all.disable_ipv6=1
    networks:
      channel:
        ipv4_address: 10.0.0.3
        
  mallory:
      image: nginx
      container_name: mallory
      tty: true
      ports:
        - "8081:80"
      volumes:
          - .:/usr/share/nginx/html:ro
      networks:
        channel:
          ipv4_address: 10.0.0.4

networks:
  channel:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24